# Generated by Django 4.2 on 2023-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('employer', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=256)),
                ('views', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
