# Generated by Django 4.2 on 2023-04-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=' Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nobis sequi aperiam necessitatibus porro, velit, quidem perspiciatis architecto eius omnis voluptates minus. Ipsum neque dolores veritatis sequi distinctio, tenetur ad. ', max_length=500),
            preserve_default=False,
        ),
    ]
