# Generated by Django 4.2 on 2023-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Information technology', 'Information technology'), ('Education', 'Education'), ('Accounting', 'Accounting')], default='Education', max_length=60),
        ),
    ]
